name: Bash Script
on:
  workflow_dispatch:

env:
  DO_NOT_TRACK: 1
jobs:
  bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Bash script
        run: |
          echo 123
          echo $DO_NO_TRACK
          echo var.DO_NOT_TRACK ${{ vars.DO_NOT_TRACK }}
