name: Bash Script
on:
  workflow_dispatch:

jobs:
  bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Bash script
        run: |
          echo 123
          echo $DO_NO_TRACK
          echo var.ENVCONTEXT_VAR ${{ vars.ENV_CONTEXT_VAR }}
